# Generated by Django 5.2 on 2025-04-26 22:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transcribe", "0002_transcriptionsummary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audiofile",
            old_name="audio_url",
            new_name="content",
        ),
    ]
